### PR TITLE
Install libraw as a replacement for ufraw

### PR DESCRIPTION
**Pull request by d7415**
Not sure whether this will work. There's a testing image available at `lycheeorg/lychee:gha-libraw`. Feedback welcome!

### CODE REVIEW

**Comment by ildyria** [comment]
https://github.com/ImageMagick/ImageMagick/issues/1617#issuecomment-505850288
Doesn't this need imagick recompilation?

**Comment by d7415** [comment]
> Doesn't this need imagick recompilation?

Hence asking for people to test... That's also why I included the binary package.

**Comment by tmp-hallenser** [comment]
Gave it a try (CR2 file):

```
    2020-11-29 06:28:33 -- error   -- App\Image\ImagickHandler::crop -- 170 -- unable to open image `/tmp/lycheemoU5x9.jpeg': No such file or directory @ error/blob.c/OpenBlob/2924
    2020-11-29 06:28:33 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is 38a40394755d63add63d5ee8296e6fdb.CR2
    2020-11-29 06:28:33 -- error   -- App\Image\GdHandler::createImage -- 303 -- Type of photo "7" is not supported
    2020-11-29 06:28:33 -- error   -- App\Image\ImagickHandler::scale -- 124 -- unable to open image `/tmp/magick-hkRN9zHEFPstgbpiLEjJ9kUSVTA2HML3.ppm': No such file or directory @ error/blob.c/OpenBlob/2924
    2020-11-29 06:28:33 -- notice  -- App\ModelFunctions\PhotoFunctions::createJpgFromRaw -- 526 -- Saving JPG of raw file to /tmp/lycheemoU5x9.jpeg
```

HEIC files though are working (guess they don't need ufraw)

**Comment by tmp-hallenser** [comment]
Did anyone try to install ufraw by compiling the source? http://ufraw.sourceforge.net/Install.html

**Comment by d7415** [comment]
> Did anyone try to install ufraw by compiling the source? http://ufraw.sourceforge.net/Install.html

I have no plans to release that - the Debian logic for removing it seems sound https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931725

**Comment by tmp-hallenser** [comment]
> > Did anyone try to install ufraw by compiling the source? http://ufraw.sourceforge.net/Install.html
> 
> I have no plans to release that - the Debian logic for removing it seems sound https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931725

ups ... fair point

**Comment by d7415** [comment]
Yeah, I probably should have put the reference earlier in this PR/somewhere. I think I discussed it with ildyria on gitter and forgot it wasn't here too.

**Comment by ildyria** [comment]
Close ? :')

**Comment by d7415** [comment]
Yeah, probably.

**Pull request closed without merging**
