### PR TITLE
improved regex deletion

### LINKED ISSUE #178: Full source code in the docker image
I took a closer look at the docker image today and noticed that the entire code including github workflows etc. is contained in the docker image and not just the finished source code.

The docker image would be smaller if only the required code was transferred

https://github.com/LycheeOrg/Lychee-Docker/blob/d10de82598ff3b696aa3a5b47fa17cd02b2b46d7/Dockerfile#L81-L83
the last line should be enough

image

### PR DESCRIPTION
**Pull request by ildyria**
Fixes #178

### CODE REVIEW

**Comment by ildyria** [comment]
```sh
root@e7d513f87a2f:/var/www/html/Lychee# find /var/www/html/Lychee -regex '.*/[Tt]ests?/.*' | wc
    282     284   18558
root@e7d513f87a2f:/var/www/html/Lychee# find . -regex '.*/[Tt]ests?/.*' | wc
    282     284   13200
root@e7d513f87a2f:/var/www/html/Lychee# find /var/www/html/Lychee -wholename '*/[Tt]ests?/*' | wc
      0       0       0
root@e7d513f87a2f:/var/www/html/Lychee# find /var/www/html/Lychee -wholename '*/[Tt]ests/*' | wc
    230     232   14288
root@e7d513f87a2f:/var/www/html/Lychee# find /var/www/html/Lychee -wholename '*/[Tt]est/*' | wc
     52      52    4270
```

**Comment by d7415** [comment]
I just built this and the tests folder is still there with all the samples :(

**Comment by d7415** [comment]
FWIW the old `find` but with pull path instead of `.` doesn't work either. I'll try to look at what `find` finds during the build when I get a chance, to check it's actually trying to delete. Running the old find from within the finished container deletes everything in the tests directory (but not the directory itself).

**Comment by ildyria** [comment]
> Running the old find from within the finished container deletes everything in the tests directory (but not the directory itself).

It is more than just THAT test directory, it is aimed to target all the test directory in the `vendor`.

**Comment by d7415** [comment]
> It is more than just THAT test directory, it is aimed to target all the test directory in the `vendor`.

Yeah, but that one's easy to test and big.

**Pull request closed without merging**
